paths:
  training_root:     data/training
  operational_root:  data/operational
  models:            data/models
  serving:           data/serving
  xai:               data/xai
  logs:              logs/

gadm:
  paths:
    raw:     data/training/raw/boundaries
    curated: data/training/curated/boundaries
  filename_gpkg: "gadm41_DZA.gpkg"
  admin_levels:
    - 0   # country
    - 1   # wilaya 
    - 2   # commune

dem:
  paths:
    raw:     data/training/raw/dem
    curated: data/training/curated/dem
  filename: "algeria_dem.tif"

worldpop:
  paths:
    raw:     data/training/raw/worldpop
    curated: data/training/curated/worldpop
  filename: "dza_pd_2020_1km_UNadj.tif"

osm:
  paths:
    raw:     data/training/raw/roads
    curated: data/training/curated/roads
  filename: "algeria-260706.osm.pbf"

landcover:
  paths:
    raw:     data/training/raw/landcover
    curated: data/training/curated/landcover

era5:
  paths:
    raw_training:         data/training/raw/era5
    curated_training:     data/training/curated/era5
    raw_operational:      data/operational/raw/era5
    curated_operational:  data/operational/curated/era5

sentinel:
  gee_project: "ai-disaster-management-502014"
  paths:
    raw_training:         data/training/raw/sentinel
    curated_training:     data/training/curated/sentinel
    raw_operational:      data/operational/raw/sentinel
    curated_operational:  data/operational/curated/sentinel

firms:
  paths:
    raw_training:         data/training/raw/firms
    curated_training:     data/training/curated/firms
    raw_operational:      data/operational/raw/firms
    curated_operational:  data/operational/curated/firms
  sensors:
    - VIIRS_SNPP_SP
    - VIIRS_NOAA20_SP
  sensors_nrt:
    - VIIRS_SNPP_NRT
    - VIIRS_NOAA20_NRT
    - VIIRS_NOAA21_NRT


logging:
  level: "INFO"
  file:  "logs/pipeline.log"

training:
  start_date: "2015-01-01"
  end_date:   "2025-12-31"
  fire_season_only:   true
  fire_season_months: [5, 6, 7, 8, 9, 10]
  integrated:         data/training/integrated
  engineered:         data/training/engineered

operational:
  era5_lag_days:     7
  firms_lag_hours:   3
  sentinel_lag_days: 5
  schedule_hour:     5
  schedule_minute:   0

algeria:
  bbox:              [-8.67, 18.96, 11.99, 37.09]
  crs:               "EPSG:4326"
  grid_resolution_m: 1000